// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://scmudsgapgsmuuiopssc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNjbXVkc2dhcGdzbXV1aW9wc3NjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNTQ1ODQsImV4cCI6MjA3MjczMDU4NH0.lRISVItwKmu3uvrsfpZS3c3097PQBFejNRy5lwGGQjA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});